version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
  
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433"
    
    environment:
      MSSQL_SA_PASSWORD: "Justas1234567!"
      MSSQL_PID: 'Developer'
      ACCEPT_EULA: "Y"